"use client";

import React from "react";

const BackgroundDoodles = () => {
  // Define doodle configurations with coding-themed symbols
  const doodles = [
    // Top section
    {
      type: "text",
      content: "{}",
      size: 3,
      top: "8%",
      left: "5%",
      color: "green-brand",
      opacity: 0.05,
      rotation: 0,
    },
    {
      type: "text",
      content: "</>",
      size: 2,
      top: "12%",
      left: "15%",
      color: "blue-400",
      opacity: 0.04,
      rotation: 15,
    },
    {
      type: "text",
      content: "( )",
      size: 3,
      top: "6%",
      left: "85%",
      color: "purple-400",
      opacity: 0.04,
      rotation: 30,
    },
    {
      type: "text",
      content: ";",
      size: 2,
      top: "15%",
      left: "92%",
      color: "pink-400",
      opacity: 0.03,
      rotation: 0,
    },
    {
      type: "text",
      content: "[ ]",
      size: 4,
      top: "10%",
      right: "25%",
      color: "green-brand",
      opacity: 0.03,
      rotation: 45,
    },
    {
      type: "text",
      content: "=>",
      size: 2,
      top: "5%",
      left: "40%",
      color: "cyan-400",
      opacity: 0.04,
      rotation: 10,
    },
    {
      type: "text",
      content: "{}",
      size: 2,
      top: "14%",
      left: "70%",
      color: "yellow-400",
      opacity: 0.03,
      rotation: 25,
    },
    {
      type: "text",
      content: ";",
      size: 2,
      top: "9%",
      left: "60%",
      color: "orange-400",
      opacity: 0.03,
      rotation: 40,
    },
    {
      type: "text",
      content: "//",
      size: 3,
      top: "7%",
      left: "30%",
      color: "pink-400",
      opacity: 0.04,
      rotation: 5,
    },
    {
      type: "text",
      content: "( )",
      size: 2,
      top: "11%",
      left: "50%",
      color: "blue-400",
      opacity: 0.03,
      rotation: 20,
    },

    // Upper-middle section
    {
      type: "text",
      content: "//",
      size: 3,
      top: "25%",
      left: "8%",
      color: "yellow-400",
      opacity: 0.04,
      rotation: 0,
    },
    {
      type: "text",
      content: "{}",
      size: 2,
      top: "28%",
      left: "88%",
      color: "green-brand",
      opacity: 0.05,
      rotation: 60,
    },
    {
      type: "text",
      content: "=>",
      size: 2,
      top: "32%",
      left: "12%",
      color: "cyan-400",
      opacity: 0.03,
      rotation: 20,
    },
    {
      type: "text",
      content: "( )",
      size: 2,
      top: "30%",
      right: "10%",
      color: "orange-400",
      opacity: 0.04,
      rotation: 0,
    },
    {
      type: "text",
      content: ";",
      size: 2,
      top: "22%",
      left: "55%",
      color: "purple-400",
      opacity: 0.03,
      rotation: 45,
    },
    {
      type: "text",
      content: "<>",
      size: 3,
      top: "27%",
      left: "35%",
      color: "pink-400",
      opacity: 0.04,
      rotation: 15,
    },
    {
      type: "text",
      content: "[ ]",
      size: 2,
      top: "24%",
      left: "75%",
      color: "blue-400",
      opacity: 0.03,
      rotation: 30,
    },
    {
      type: "text",
      content: "{}",
      size: 2,
      top: "26%",
      left: "20%",
      color: "cyan-400",
      opacity: 0.03,
      rotation: 50,
    },
    {
      type: "text",
      content: "=>",
      size: 3,
      top: "29%",
      left: "65%",
      color: "yellow-400",
      opacity: 0.04,
      rotation: 10,
    },
    {
      type: "text",
      content: ";",
      size: 2,
      top: "23%",
      left: "42%",
      color: "green-brand",
      opacity: 0.03,
      rotation: 35,
    },

    // Middle section
    {
      type: "text",
      content: "<>",
      size: 3,
      top: "45%",
      left: "6%",
      color: "purple-400",
      opacity: 0.05,
      rotation: 90,
    },
    {
      type: "text",
      content: "{ }",
      size: 2,
      top: "48%",
      left: "90%",
      color: "pink-400",
      opacity: 0.03,
      rotation: 35,
    },
    {
      type: "text",
      content: "/**/",
      size: 4,
      top: "50%",
      left: "18%",
      color: "green-brand",
      opacity: 0.04,
      rotation: 0,
    },
    {
      type: "text",
      content: "=>",
      size: 2,
      top: "52%",
      right: "15%",
      color: "blue-400",
      opacity: 0.04,
      rotation: 45,
    },
    {
      type: "text",
      content: "[ ]",
      size: 3,
      top: "55%",
      left: "85%",
      color: "yellow-400",
      opacity: 0.03,
      rotation: 60,
    },
    {
      type: "text",
      content: "{}",
      size: 2,
      top: "42%",
      left: "45%",
      color: "cyan-400",
      opacity: 0.04,
      rotation: 20,
    },
    {
      type: "text",
      content: "//",
      size: 2,
      top: "47%",
      left: "60%",
      color: "orange-400",
      opacity: 0.03,
      rotation: 50,
    },
    {
      type: "text",
      content: ";",
      size: 2,
      top: "53%",
      left: "30%",
      color: "pink-400",
      opacity: 0.03,
      rotation: 10,
    },
    {
      type: "text",
      content: "( )",
      size: 2,
      top: "44%",
      left: "72%",
      color: "purple-400",
      opacity: 0.03,
      rotation: 25,
    },
    {
      type: "text",
      content: "</>",
      size: 3,
      top: "49%",
      left: "38%",
      color: "blue-400",
      opacity: 0.04,
      rotation: 15,
    },
    {
      type: "text",
      content: "=>",
      size: 2,
      top: "51%",
      left: "8%",
      color: "yellow-400",
      opacity: 0.03,
      rotation: 40,
    },
    {
      type: "text",
      content: "{}",
      size: 2,
      top: "46%",
      left: "25%",
      color: "green-brand",
      opacity: 0.03,
      rotation: 30,
    },

    // Lower-middle section
    {
      type: "text",
      content: "( )",
      size: 2,
      top: "65%",
      left: "10%",
      color: "cyan-400",
      opacity: 0.04,
      rotation: 0,
    },
    {
      type: "text",
      content: "</>",
      size: 2,
      top: "68%",
      left: "88%",
      color: "orange-400",
      opacity: 0.03,
      rotation: 120,
    },
    {
      type: "text",
      content: "{}",
      size: 3,
      top: "70%",
      left: "7%",
      color: "green-brand",
      opacity: 0.04,
      rotation: 25,
    },
    {
      type: "text",
      content: ";",
      size: 2,
      top: "72%",
      right: "12%",
      color: "purple-400",
      opacity: 0.05,
      rotation: 0,
    },
    {
      type: "text",
      content: "=>",
      size: 2,
      top: "62%",
      left: "50%",
      color: "blue-400",
      opacity: 0.03,
      rotation: 35,
    },
    {
      type: "text",
      content: "[ ]",
      size: 3,
      top: "67%",
      left: "35%",
      color: "yellow-400",
      opacity: 0.04,
      rotation: 15,
    },
    {
      type: "text",
      content: "<>",
      size: 2,
      top: "71%",
      left: "65%",
      color: "pink-400",
      opacity: 0.03,
      rotation: 40,
    },
    {
      type: "text",
      content: "//",
      size: 2,
      top: "64%",
      left: "22%",
      color: "cyan-400",
      opacity: 0.03,
      rotation: 55,
    },
    {
      type: "text",
      content: "{}",
      size: 2,
      top: "69%",
      left: "78%",
      color: "orange-400",
      opacity: 0.04,
      rotation: 20,
    },
    {
      type: "text",
      content: ";",
      size: 2,
      top: "66%",
      left: "55%",
      color: "green-brand",
      opacity: 0.03,
      rotation: 45,
    },

    // Bottom section
    {
      type: "text",
      content: "//",
      size: 3,
      top: "82%",
      left: "14%",
      color: "pink-400",
      opacity: 0.04,
      rotation: 150,
    },
    {
      type: "text",
      content: "=>",
      size: 3,
      top: "85%",
      left: "82%",
      color: "blue-400",
      opacity: 0.03,
      rotation: 0,
    },
    {
      type: "text",
      content: "[ ]",
      size: 2,
      top: "88%",
      left: "9%",
      color: "yellow-400",
      opacity: 0.04,
      rotation: 40,
    },
    {
      type: "text",
      content: "<>",
      size: 2,
      top: "90%",
      right: "8%",
      color: "green-brand",
      opacity: 0.05,
      rotation: 75,
    },
    {
      type: "text",
      content: "( )",
      size: 2,
      top: "92%",
      left: "88%",
      color: "cyan-400",
      opacity: 0.03,
      rotation: 0,
    },
    {
      type: "text",
      content: "{}",
      size: 3,
      top: "78%",
      left: "45%",
      color: "purple-400",
      opacity: 0.04,
      rotation: 20,
    },
    {
      type: "text",
      content: ";",
      size: 2,
      top: "84%",
      left: "55%",
      color: "orange-400",
      opacity: 0.03,
      rotation: 60,
    },
    {
      type: "text",
      content: "//",
      size: 2,
      top: "95%",
      left: "30%",
      color: "cyan-400",
      opacity: 0.04,
      rotation: 10,
    },
    {
      type: "text",
      content: "=>",
      size: 2,
      top: "80%",
      left: "68%",
      color: "pink-400",
      opacity: 0.03,
      rotation: 25,
    },
    {
      type: "text",
      content: "( )",
      size: 2,
      top: "86%",
      left: "25%",
      color: "blue-400",
      opacity: 0.04,
      rotation: 35,
    },
    {
      type: "text",
      content: "</>",
      size: 3,
      top: "91%",
      left: "60%",
      color: "yellow-400",
      opacity: 0.03,
      rotation: 50,
    },

    // Additional scattered doodles
    {
      type: "text",
      content: ";",
      size: 2,
      top: "20%",
      left: "50%",
      color: "orange-400",
      opacity: 0.03,
      rotation: 55,
    },
    {
      type: "text",
      content: "{}",
      size: 2,
      top: "40%",
      left: "45%",
      color: "pink-400",
      opacity: 0.04,
      rotation: 0,
    },
    {
      type: "text",
      content: "//",
      size: 2,
      top: "60%",
      left: "48%",
      color: "purple-400",
      opacity: 0.04,
      rotation: 30,
    },
    {
      type: "text",
      content: "=>",
      size: 2,
      top: "75%",
      left: "52%",
      color: "blue-400",
      opacity: 0.03,
      rotation: 70,
    },
    {
      type: "text",
      content: "( )",
      size: 2,
      top: "35%",
      left: "22%",
      color: "green-brand",
      opacity: 0.04,
      rotation: 15,
    },
    {
      type: "text",
      content: "[ ]",
      size: 3,
      top: "58%",
      left: "78%",
      color: "yellow-400",
      opacity: 0.03,
      rotation: 25,
    },
    {
      type: "text",
      content: "<>",
      size: 2,
      top: "18%",
      left: "82%",
      color: "cyan-400",
      opacity: 0.03,
      rotation: 60,
    },
    {
      type: "text",
      content: ";",
      size: 2,
      top: "38%",
      left: "12%",
      color: "orange-400",
      opacity: 0.03,
      rotation: 10,
    },
    {
      type: "text",
      content: "{}",
      size: 2,
      top: "56%",
      left: "92%",
      color: "pink-400",
      opacity: 0.04,
      rotation: 45,
    },
  ];

  const renderDoodle = (doodle: (typeof doodles)[0], index: number) => {
    const baseClasses = "absolute pointer-events-none";

    // Create varied animation durations and delays for organic movement
    const animationDuration = 3 + (index % 5); // 3-7 seconds
    const animationDelay = (index % 10) * 0.5; // 0-4.5 seconds delay

    const style: React.CSSProperties = {
      top: doodle.top,
      left: doodle.left,
      right: (doodle as any).right,
      opacity: doodle.opacity,
      transform: `rotate(${doodle.rotation}deg)`,
      animation: `float ${animationDuration}s ease-in-out ${animationDelay}s infinite`,
      fontSize: `${doodle.size * 8}px`,
      color: getColorValue(doodle.color),
      fontFamily: "monospace",
      fontWeight: "bold",
      lineHeight: 1,
    };

    return (
      <div key={index} className={baseClasses} style={style}>
        {doodle.content}
      </div>
    );
  };

  const getColorValue = (color: string) => {
    const colorMap: Record<string, string> = {
      "green-brand": "#77FF94",
      "blue-400": "#60a5fa",
      "purple-400": "#c084fc",
      "pink-400": "#f472b6",
      "yellow-400": "#facc15",
      "cyan-400": "#22d3ee",
      "orange-400": "#fb923c",
    };
    return colorMap[color] || "#77FF94";
  };

  return (
    <>
      <style jsx>{`
        @keyframes float {
          0%, 100% {
            transform: translateY(0px) rotate(var(--rotation));
          }
          50% {
            transform: translateY(-20px) rotate(var(--rotation));
          }
        }
      `}</style>
      <div className="absolute inset-0 pointer-events-none overflow-hidden z-0">
        {doodles.map((doodle, index) => {
          const element = renderDoodle(doodle, index);
          if (!element) return null;

          // Add rotation CSS variable for animation
          return React.cloneElement(element, {
            style: {
              ...element.props.style,
              "--rotation": `${doodle.rotation}deg`,
            } as React.CSSProperties,
          });
        })}
      </div>
    </>
  );
};

export default BackgroundDoodles;
